name: Save Qinglong Docker Image to Release

on:
  workflow_dispatch:  # 无需输入任何参数，直接触发

jobs:
  save-docker-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.8.0

      - name: Pull Qinglong Docker image
        run: |
          docker pull whyour/qinglong:2.17.4

      - name: Save Docker image to tar file
        run: |
          docker save whyour/qinglong:2.17.4 | gzip > qinglong-2.17.4.tar.gz

      - name: Upload Docker image to GitHub Releases
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: qinglong-2.17.4.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
