name: 比较版本号

permissions:
  contents: write  # 需要写权限来创建发布
  id-token: write  # 如果需要身份令牌的写权限（可选）

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Git 仓库地址'
        required: true
        default: 'https://github.com/immortalwrt/packages'
      branch1:
        description: '第一个分支名称'
        required: true
        default: 'openwrt-21.02'
        options: [ openwrt-21.02, openwrt-23.05, openwrt-24.10, master, openwrt-18.06-k5.4, openwrt-18.06 ]
      branch2:
        description: '第二个分支名称'
        required: true
        default: 'openwrt-24.10'
        options: [ openwrt-21.02, openwrt-23.05, openwrt-24.10, master, openwrt-18.06-k5.4, openwrt-18.06 ]

jobs:
  compare_versions:
    runs-on: ubuntu-latest
    name: ${{github.event.inputs.repo_url}} ${{github.event.inputs.branch1}} ${{github.event.inputs.branch2}} 版本号比较

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v2

      - name: 设置 Git
        run: |
          git fetch --all

      - name: 比较 Makefile 版本号
        run: |
          REPO_URL="${{ github.event.inputs.repo_url }}"
          BRANCH1="${{ github.event.inputs.branch1 }}"
          BRANCH2="${{ github.event.inputs.branch2 }}"
          
          # 克隆用户指定的仓库
          git clone -q "$REPO_URL"
          REPO_NAME=$(basename "$REPO_URL" .git)
          cd "$REPO_NAME"

          # 拉取远程的分支
          git fetch origin
          git checkout "$BRANCH1"
          git pull origin "$BRANCH1"
          git checkout "$BRANCH2"
          git pull origin "$BRANCH2"
          
          # 创建报告文件并输出到控制台
          echo "$REPO_URL $BRANCH1 $BRANCH2 版本号比较" | tee ../comparison.txt
          echo "=====================================" | tee -a ../comparison.txt

          # 获取两个分支中所有 Makefile 文件的差异
          makefiles=$(git diff --name-only "$BRANCH1".."$BRANCH2" -- '**/Makefile')
          for makefile in $makefiles; do

            # 获取 Makefile 所在目录的上一级目录名
            package_name=$(dirname "$makefile" | xargs basename)

            # 提取第一个分支的版本号
            version1=$(git show "$BRANCH1:$makefile" 2>/dev/null | sed -En 's/^PKG_VERSION:=(.*)/\1/p' 2>/dev/null)

            # 提取第二个分支的版本号
            version2=$(git show "$BRANCH2:$makefile" 2>/dev/null | sed -En 's/^PKG_VERSION:=(.*)/\1/p' 2>/dev/null)

            # 如果版本号包含 '$(' 或 ')', 则清空版本号
            if [[ "$version1" =~ \$\(.*\) ]]; then
              version1=""
            fi

            if [[ "$version2" =~ \$\(.*\) ]]; then
              version2=""
            fi

            # 比较版本号
            if [ "$version1" != "$version2" ]; then
              echo "-------------------------------------------------" | tee -a ../comparison.txt
              echo "包名: $package_name" | tee -a ../comparison.txt
              echo "$BRANCH1 分支的版本号: ${version1:-不存在}" | tee -a ../comparison.txt
              echo "$BRANCH2 分支的版本号: ${version2:-不存在}" | tee -a ../comparison.txt
              echo "$package_name 包的版本号不同!" | tee -a ../comparison.txt
            fi
            echo "-------------------------------------------------" | tee -a ../comparison.txt
          done

      - name: 创建 GitHub Release 并上传报告
        uses: softprops/action-gh-release@v2.0.9
        with:
          files: comparison.txt
          name: 比较版本
          tag_name: comparison
          token: ${{secrets.GITHUB_TOKEN}}
